# Generated by Django 5.2.1 on 2025-06-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_username_laptime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username',
            name='email',
        ),
    ]
