# Generated by Django 5.2.3 on 2025-07-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_username_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='username',
            old_name='laptime',
            new_name='lap1',
        ),
        migrations.AddField(
            model_name='username',
            name='lap2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='username',
            name='lap3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='username',
            name='total_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
